HUB_DOMAIN: "xr.icer.kyushu-u.ac.jp"
ADM_EMAIL: "cloud12817@gmail.com"
Namespace: "hcce"
Container_Dockerhub_Username: "mozillareality"
Container_Tag: "stable-latest"
DB_USER: "postgres"
DB_PASS: "123456"
DB_NAME: "retdb"
DB_HOST: "pgbouncer"
DB_HOST_T: "pgbouncer-t"
PGRST_DB_URI: "postgres://$DB_USER:$DB_PASS@pgbouncer/$DB_NAME"
PSQL: "postgres://$DB_USER:$DB_PASS@pgbouncer/$DB_NAME"
SMTP_SERVER: "hosting7.icer.kyushu-u.ac.jp"
SMTP_PORT: "587"
SMTP_USER: "contsrv_admin@icer.kyushu-u.ac.jp"
SMTP_PASS: "r$9)SFQR+I($"
NODE_COOKIE: "tkWfbAijhLkCzthN"
GUARDIAN_KEY: "kcZvzegZujPjzkrr"
PHX_KEY: "szgRYSejRyMmCTQC"
SKETCHFAB_API_KEY: "?"
TENOR_API_KEY: "?"
GENERATE_PERSISTENT_VOLUMES: "Yes"
PERSISTENT_VOLUME_STORAGE_CLASS: "default"   # or 'manual' for a single-node test installations
PERSISTENT_VOLUME_SIZE: "10Gi"
OVERRIDE_RETICULUM_IMAGE: "hubsfoundation/reticulum:$Container_Tag"
OVERRIDE_POSTGREST_IMAGE: "No"
OVERRIDE_POSTGRES_IMAGE: "No"
OVERRIDE_PGBOUNCER_IMAGE: "No"
OVERRIDE_HUBS_IMAGE: "hubsfoundation/hubs:$Container_Tag"
OVERRIDE_SPOKE_IMAGE: "hubsfoundation/spoke:$Container_Tag"
OVERRIDE_NEARSPARK_IMAGE: "No"
OVERRIDE_PHOTOMNEMONIC_IMAGE: "No"
OVERRIDE_DIALOG_IMAGE: "No"
OVERRIDE_COTURN_IMAGE: "No"
OVERRIDE_HAPROXY_IMAGE: "No"
